[package]
name = "runic"
version = "0.1.0"
edition = "2021"

# [patch.crates-io]
# egui = { path = "../clone/egui/crates/egui" }

[lib]

[[example]]
name = "ex1"

[dependencies]
bevy_app = "0.19"
bevy_asset = "0.19"
bevy_ecs = "0.19"
bevy_egui = { version = "0.41", features = ["serde"] }
bevy_image = "0.19"
bevy_math = "0.19"
bevy_reflect = "0.19"
bevy_render = "0.19"
bitflags = { version = "2.6.0", features = ["serde"] }
itertools = "0.15"
serde = { version = "1", features = ["derive"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }

[dev-dependencies]
bevy = {
  version = "0.19",
  default-features = false,
  # Do we need 2d? Not for ui but maybe for egui?
  features = ["audio", "ui"]
}
