[package]
name = "runic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
eframe = "0.18.0"
egui = "0.18.1"
egui_extras = { version = "0.18.0", features = ["image"] }
image = { version = "0.24.3", features = ["png"], default-features = false }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
